### PR TITLE
fix(boolean ops): fix && ops

### PR DESCRIPTION
**Pull request by ngochai94**
Thanks for the awesome extensions! We just started using your library and came across a minor typo. This PR will fix it.

### CODE REVIEW

**Comment by yurique** [comment]
Oh wow, nice catch! Thanks @ngochai94! I'll release a fix asap.

**Comment by yurique** [comment]
@ngochai94 0.12.2 is released and should be on maven central. Thanks again!

**Comment by yurique** [comment]
The release was bumpy this time (sonatype returned a [weird error](https://github.com/tulz-app/laminext/runs/2181614137?check_suite_focus=true) at the end of the release process) – but it looks like it was successful after all. Please let me know if something's not right.

**Comment by ngochai94** [comment]
thanks @yurique !

**Pull request merged**
