### PR TITLE
Expose ws protocol

### LINKED ISSUE #36: Expose WebSocket protocol
The JavaScript websocket is defined with 2 arguments, `url` and `protocol`:
```scala
class WebSocket(var url: String = js.native, var protocol: String = js.native)
```
But Laminext doesn't allow setting the protocol:
```scala
val ws = new raw.WebSocket(url)
```

### PR DESCRIPTION
**Pull request by ghostdogpr**
Closes #36

### CODE REVIEW

**Comment by yurique** [comment]
@ghostdogpr thanks! I wasn't aware there was such a thing.

What's interesting, MDN says one can provide multiple protocols for the server to choose from: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket, but we don't have it in scalajs-dom, so just one will have to do.

**Comment by ghostdogpr** [comment]
Yeah I tried to use an array of strings first but realized it was expecting a single string.

**Comment by yurique** [comment]
@ghostdogpr 0.13.2 is out

**Comment by ghostdogpr** [comment]
Awesome! FYI https://twitter.com/ghostdogpr/status/1396278131619631109?s=21 It works like a charm 😍

**Comment by yurique** [comment]
Nice!

**Pull request merged**
